# main text of home
title: Emanuele Santos
name: Emanuele Santos
bio: Computer Scientist & Visualization Researcher

# twitter summary info
description: Emanuele's online home

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: true
resume-url: http://lattes.cnpq.br/3334643879272311

baseurl: "" # the subpath of your site, e.g. /blog
url: https://emanueles.github.io
# your url: http://USERNAME.github.io

permalink: /:title/



# To enable google analytics, supply your token below
analytics-google: 'UA-107602706-1'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, set to false
#disqus: mydisqus

# if you don't have any of social below, comment the line
#facebook: myfacebook
twitter: emanueles
# google: mygoogle
instagram: prof.manu.ufc
# pinterest: mypinterest
# linkedin: mylinkedin
youtube: EmanueleSantos09
#spotify: myspotify
github: emanueles
#stackoverflow: 7044681/mystackoverflow
#quora: userquora
#reddit: username
#medium: medium
#vimeo: myvimeo
lattes: "3334643879272311"
email: emanuele@dc.ufc.br

authors:
    emanuele:
        name: Emanuele Santos
        bio: Computer Scientist & Visualization Researcher
        external-image: false
        picture: assets/images/profile.jpg
        twitter: emanueles
    # jamesfoster:
    #     name: James Foster
    #     bio: A Man who develops software with coffee
    #     external-image: false
    #     picture: assets/images/james.jpg
    #     twitter: jamesfoster

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

timezone: America/Fortaleza

# if you do/don't need pagination, toggle 'enabled' between true/false below
pagination:
  enabled: true
  title: ":title" # Changing this will mess up the header display logic
  per_page: 5
  permalink: '/:num/' # pagination link that will be appended
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true # display recent posts first
  trail: 
    before: 2
    after: 2

# if you don't need projects, comment the *projects* configs below
projects: true
teaching: true
talks: true
students: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true
pub: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

collections:
  publications:
    output: true
    permalink: /publications/:path/
  projs:
    output: true
    permalink: /projs/:path/

autopages:
  enabled: true
  tags: 
    layouts: 
      - autopage_collections_tags.html
     # - autopage_tags.html
    enabled: true
  categories:
    layouts:
      - autopage_cat.html
    enabled: true
  collections:
    enabled: true
# This site uses the pretty permalink structure, this renders all urls with a slash / at the end and 
# no file endings, I guess that is considered pretty :)
permalink: pretty

# add default values to specific pages or layouts
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      layout: "post"
    values:
      # setting all post to not hidden by default,
      # can be overridden in the front matter for a specific post
      hidden: false


plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
  - jekyll-paginate-v2

jekyll-mentions:
  base_url: https://github.com

compress_html:
  ignore:
    envs:
      - development
      - stage

exclude:
  [
    "travis.sh",
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    "node_modules",
    "vendor",
    "drafts"
  ]
